### ISSUE TITLE
subtract skipped tests

### ISSUE THREAD

**Issue by megies** [obspy/reporter#11]
The number of "Tests" shown on the web page should not include the skipped tests, IMHO. The title of the column should probably also be changed to e.g. "Executed". Compare http://tests.obspy.org/18282/ (missed matplotlib, so some `station` and `core` tests were skipped) and http://tests.obspy.org/18283/:

![screenshot from 2014-11-19 13 08 51](https://cloud.githubusercontent.com/assets/1842780/5105457/476d7ace-6fed-11e4-907c-d3fb7837adb6.png)
![screenshot from 2014-11-19 13 09 04](https://cloud.githubusercontent.com/assets/1842780/5105456/47694544-6fed-11e4-82bf-a2b46277ef3d.png)

Especially in the overview page it's misleading to see the number of all "tried" tests (which is the same for the two above runs) and not the number of actually executed tests (which is different for the two above runs):

![screenshot from 2014-11-19 13 11 55](https://cloud.githubusercontent.com/assets/1842780/5105492/bfa0e15c-6fed-11e4-8212-a7a862c4d2d5.png)

**Comment by barsch** [comment]
fixed in latest commits
