### ISSUE TITLE
add CI-URL and PR-URL to front-page overview table

### ISSUE THREAD

**Issue by megies** [obspy/reporter#12]
can be two very slim columns

| CI        | PR           |
| ------------- |:-------------:|
| [Tra](https://travis-ci.org/obspy/obspy/builds/110174170)      | [#123](https://github.com/obspy/obspy/pull/1269) |
| ---      | [#1245](https://github.com/obspy/obspy/pull/1269)      |
| [Apv](https://ci.appveyor.com/project/obspy/obspy/build/1.0.1692-runtest_report_ci_url) | ---      |

**Comment by barsch** [comment]
fixed in latest commits

**Comment by megies** [comment]
Nice! :+1:
