### ISSUE TITLE
Public interest on test reporter setup

### ISSUE THREAD

**Issue by megies** [obspy/reporter#18]
Various people at EuroScipy 2016 seemed pretty interested in the whole test reporting and visualization setup. Might be worth a thought to further generalize/push/advertize this piece of our workflow..

CC @krischer

**Comment by barsch** [comment]
its currently pretty tailored to obspy - so don't know if its worth the effort - but I leave the ticket open, so if someone is really interested into a more general package than he/she should leave a comment!
