### ISSUE TITLE
Possible to include test report number in response?

### ISSUE THREAD

**Issue by megies** [obspy/reporter#19]
Is it possible (and not too much work) to include the test report number from the server in the http response? We could include a link to the report in the "`Test report has been sent to tests.obspy.org. Thank you!`" message then..

**Comment by barsch** [comment]
on successful submission (```response.status==200```) a JSON response will be delivered containing the report page URL - json allows us later to extend it - if needed ...

e.g. on my local test server:
```python
>>> response.reason
'OK'
>>> response.status
200
>>> response.type
'application/json'
>>> import json
>>> json.loads(response.read())
{u'url': u'http://127.0.0.1/51416/'}
```
