### ISSUE TITLE
add "gh-actions" as clickable node filter

### ISSUE THREAD

**Issue by megies** [obspy/reporter#21]
No hurry at all, but might be good to have `gh-actions` as clickable node filter since we likely switch all CI over to there see obspy/obspy#2591
Didn't see it in the source code here, so I'm guessing it's in the database?

![Screenshot from 2020-07-03 10-06-17](https://user-images.githubusercontent.com/1842780/86446922-e1973480-bd14-11ea-9d62-3523c42c2bb6.png)

**Comment by megies** [comment]
Maybe also move the nodes to before Python versions, since that list is really long and you can only see the node filter by scrolling way down.

Another good thing would be a tiny hint at other filtering options..
 - `pr=...`
 - `module=...`
 - `git=`

https://github.com/obspy/reporter/blob/af98fe756615fe888a0ba25867e7a97017e1dcf4/src/reporter/core/views.py#L148

**Comment by barsch** [comment]
all implemented

**Comment by megies** [comment]
:rocket: :tada
