### ISSUE TITLE
code links in skipped and slowest not working

### ISSUE THREAD

**Issue by trichter** [obspy/reporter#23]
@barsch Thanks for the latest very fast fixes!

Because the test root dir is the obspy folder now, some code links do not work anymore for new reports.

For example

https://github.com/obspy/obspy/blob/1.3.0a1/clients/fdsn/tests/test_client.py#L1598

should instead be

https://github.com/obspy/obspy/blob/1.3.0a1/obspy/clients/fdsn/tests/test_client.py#L1598

**Comment by barsch** [comment]
do you have an existing report with failing links which I can use as reference? I checked like 20 or so latest reports with failures but all links I checked worked for me ...

**Comment by trichter** [comment]
It's not about the failures. These links are are working. It's about the links in skipped and slowest tests.
