### ISSUE TITLE
some modules' tests shown combined unter "other"

### ISSUE THREAD

**Issue by megies** [obspy/reporter#25]
Not sure whats going on but somehow some tests get grouped into `"other"`..

https://tests.obspy.org/138411/

![Screenshot from 2024-05-14 16-25-42](https://github.com/obspy/reporter/assets/1842780/f90e6e3f-55c6-434b-8e79-3967113089d6)

some "client." modules missing at top..

![Screenshot from 2024-05-14 16-26-46](https://github.com/obspy/reporter/assets/1842780/b14b9df0-3476-4018-bf50-833f8bd58b30)

and got grouped under "other" at bottom

**Comment by barsch** [comment]
seems like the pytest JSON structure has changed a bit - anyway should be fixed now - I'm currently re-indexing the whole archive - will take a while

please reopen if the issue persist for new reports!

**Comment by megies** [comment]
Looking good, thanks :heart:
