### ISSUE TITLE
what to do with too large reports

### ISSUE THREAD

**Issue by megies** [obspy/reporter#26]
I've seen CI test reports not getting sent because their payload is too big, likely because of the tracebacks (pytest and decorators blowing tracebacks up massively, sadly). In [this case](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=942855&view=logs&j=d1321064-f6c3-56b7-0172-6d994d01c836&t=22462ed5-0c01-589f-e980-ef3bedbf8119&l=22990) it's "just" 77 test fails.

```
Error: Could not sent a test report to tests.obspy.org.
Bad Request
b'Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.'
```

![Screenshot from 2024-05-27 10-34-09](https://github.com/obspy/reporter/assets/1842780/434a9b42-598d-49ac-bd15-f8aee29f3129)

Not sure what to do. I guess aside from allowing larger reports, we could maybe in our obspy reporting code handle a response like that and send the report again without tracebacks maybe?

CC @trichter @barsch

**Comment by barsch** [comment]
that is just a server side setting which can be increased, see https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-DATA_UPLOAD_MAX_MEMORY_SIZE

default is atm 2621440 (2.5 MB) - any idea how big the payload for the failing tests is?

**Comment by barsch** [comment]
ok increased to 10 MB for now - please test

**Comment by megies** [comment]
Looks like those reports that couldnt get sent are sent now, thanks!
