### ISSUE TITLE
submodule filter

### ISSUE THREAD

**Issue by megies** [obspy/reporter#4]
might be nice to have sometimes to filter out tests that don't have a specific module tested. i.e. click "iris" -> only shows tests that have run iris submodule.

advanced version might be: make the pass/fail sign in the first column specific to the selected submodule. i.e. click "iris" -> only shows tests that have run iris + checkmark shows if iris passed or failed (e.g. shows "pass" even if another module produced errors).

**Comment by barsch** [comment]
general support for filtering per module is now possible: http://tests.obspy.org/?limit=20&module=clients.seishub, however I didn't include it as filter in the index page yet

**Comment by barsch** [comment]
I really don't want to include the submodules into the side menu - its already way to long ... Filtering via URL parameter is working. Closing the ticket for now.

**Comment by megies** [comment]
> general support for filtering per module is now possible: http://tests.obspy.org/?limit=20&module=clients.seishub, however I didn't include it as filter in the index page yet

thanks!

(we probably start to need some listing of possible REST parameters somewhere on the page..)
