### ISSUE TITLE
provide link to travis build

### ISSUE THREAD

**Issue by megies** [obspy/reporter#7]
We could add an option to set the [Travis job ID](http://about.travis-ci.org/docs/user/ci-environment/) in the report and have a column with a link to respective Travis build in the report overview page..
`https://travis-ci.org/${TRAVIS_REPO_SLUG}/jobs/${TRAVIS_JOB_ID}`

There is also an environment variable that stores the pull request number, we could also link that if `TRAVIS_PULL_REQUEST` is not `false`..
`https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}`

**Comment by barsch** [comment]
fixed in latest commits
